settings_version: 0.0.4
datasets_dir: /workspace/datasets
weights_dir: weights
runs_dir: runs
uuid: 6fe47a202be2cbe156421621e64193a1cab320138753658882c3d8eafb8bfcac
sync: true
api_key: ''
openai_api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
