"""Stage 07: Assemble the SD-card deploy bundle.

  artifacts/deploy/
    model.kmodel
    deploy_config.json
    det_image_yolov8.py
    det_live_xy_yolov8.py
    yolov8_decode.py
    README.md
"""
import sys, json, shutil
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from shared.config import load

DEPLOY_CONFIG_TEMPLATE = {
    "model_type": "AnchorFreeDet",
    "model_path": "/data/k230-deploy/model.kmodel",
    "input_size": [640, 480],
    "labels": ["silver", "black"],
    "obj_thresh": 0.3,
    "nms_thresh": 0.45,
    "mean": [0.0, 0.0, 0.0],
    "std": [1.0, 1.0, 1.0],
}

def main():
    cfg = load()
    p = cfg["package"]
    out = Path(p["out_dir"])
    out.mkdir(parents=True, exist_ok=True)

    winner_file = Path(cfg["eval"]["report_csv"]).parent / "winner.txt"
    if not winner_file.exists():
        print("[stage 07] no winner.txt -- run stage 06 first")
        sys.exit(2)
    winner = winner_file.read_text().strip()
    print(f"[stage 07] packaging winner: {winner}")

    exports = Path(cfg["compile"]["exports_dir"])
    src_km = exports / winner / "model.kmodel"
    shutil.copy(src_km, out / "model.kmodel")

    cfg_out = dict(DEPLOY_CONFIG_TEMPLATE)
    cfg_out["labels"] = cfg["dataset"]["names"]
    with open(out / "deploy_config.json", "w") as f:
        json.dump(cfg_out, f, indent=2)

    scripts_src = Path(p["deploy_scripts_src"])
    for name in ("det_image_yolov8.py", "det_live_xy_yolov8.py", "yolov8_decode.py"):
        s = scripts_src / name
        if s.exists():
            shutil.copy(s, out / name)
        else:
            print(f"[stage 07] WARN: {s} missing")

    readme = out / "README.md"
    readme.write_text(f"""# K230D deploy bundle (winner: {winner})

Copy ALL files in this directory to the K230D SD card at `/data/k230-deploy/`.

Then on the CanMV REPL:
    import det_image_yolov8
    det_image_yolov8.detection()

Live camera:
    import det_live_xy_yolov8
    det_live_xy_yolov8.live()

Files:
- model.kmodel           the compiled detector ({src_km.stat().st_size/1e6:.2f} MB)
- deploy_config.json     runtime config (labels, thresholds, mean/std)
- det_image_yolov8.py    single-image inference + draw boxes
- det_live_xy_yolov8.py  live camera + UART packet emission
- yolov8_decode.py       shared anchor-free decoder + NMS

Generated by k230/pipeline/stages/07_package.py.
""")
    print(f"[stage 07] DONE -> {out}")
    for f in sorted(out.iterdir()):
        sz = f.stat().st_size
        print(f"  {f.name:30s} {sz:>10,} B")

if __name__ == "__main__":
    main()
