"""Stage 07: Assemble the SD-card deploy bundle.

  artifacts/deploy/
    model.kmodel
    deploy_config.json
    det_image_yolov8.py
    det_live_xy_yolov8.py
    yolov8_decode.py
    README.md
"""
import sys, json, shutil
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from shared.config import load

# Keys here must match what det_image_yolov8.py / det_live_xy_yolov8.py read.
# Verified against a working deploy_config.json from train/exports/.
DEPLOY_CONFIG_TEMPLATE = {
    "nncase_version": "2.11.0",
    "chip_type": "k230",
    "model_type": "AnchorFreeDet",
    "kmodel_path": "model.kmodel",
    "img_size": [640, 480],
    "inference_width": 640,
    "inference_height": 480,
    "num_classes": 2,
    "categories": ["black", "silver"],   # overwritten from pipeline.yaml below
    "confidence_threshold": 0.3,
    "nms_threshold": 0.5,
    "nms_option": False,
    "mean": [0.0, 0.0, 0.0],
    "std": [1.0, 1.0, 1.0],
    "calibrate_method": "Kld",
    "ptq_option": "w:uint8 d:int16",
}

def main():
    cfg = load()
    p = cfg["package"]
    out = Path(p["out_dir"])
    out.mkdir(parents=True, exist_ok=True)

    winner_file = Path(cfg["eval"]["report_csv"]).parent / "winner.txt"
    if not winner_file.exists():
        print("[stage 07] no winner.txt -- run stage 06 first")
        sys.exit(2)
    winner = winner_file.read_text().strip()
    print(f"[stage 07] packaging winner: {winner}")

    exports = Path(cfg["compile"]["exports_dir"])
    src_km = exports / winner / "model.kmodel"
    shutil.copy(src_km, out / "model.kmodel")

    cfg_out = dict(DEPLOY_CONFIG_TEMPLATE)
    cfg_out["categories"]      = cfg["dataset"]["names"]
    cfg_out["num_classes"]     = len(cfg["dataset"]["names"])
    cfg_out["img_size"]        = [cfg["train"]["imgsz"][1], cfg["train"]["imgsz"][0]]  # [W, H]
    cfg_out["inference_width"]  = cfg["train"]["imgsz"][1]
    cfg_out["inference_height"] = cfg["train"]["imgsz"][0]
    cfg_out["_meta"] = {
        "variant": winner,
        "preprocess_mode": cfg["compile"]["preprocess_mode"],
        "use_letterbox": cfg["compile"]["use_letterbox"],
        "kmodel_size_bytes": src_km.stat().st_size,
    }
    with open(out / "deploy_config.json", "w") as f:
        json.dump(cfg_out, f, indent=2)

    scripts_src = Path(p["deploy_scripts_src"])
    # NOTE: decoder is inlined into the two deploy scripts (CanMV MicroPython
    # has no sys.path so cross-file imports don't work). Don't copy
    # yolov8_decode.py — it stays in train/src/ as canonical reference only.
    for name in ("det_image_yolov8.py", "det_live_xy_yolov8.py"):
        s = scripts_src / name
        if s.exists():
            shutil.copy(s, out / name)
        else:
            print(f"[stage 07] WARN: {s} missing")
    # Remove any stale yolov8_decode.py left over from earlier runs.
    stale = out / "yolov8_decode.py"
    if stale.exists():
        stale.unlink()

    readme = out / "README.md"
    readme.write_text(f"""# K230D deploy bundle (winner: {winner})

Copy ALL files in this directory to the K230D SD card at `/data/k230-deploy/`.

Then on the CanMV REPL:
    import det_image_yolov8
    det_image_yolov8.detection()

Live camera:
    import det_live_xy_yolov8
    det_live_xy_yolov8.live()

Files:
- model.kmodel           the compiled detector ({src_km.stat().st_size/1e6:.2f} MB)
- deploy_config.json     runtime config (labels, thresholds, mean/std)
- det_image_yolov8.py    single-image inference (decoder inlined)
- det_live_xy_yolov8.py  live camera + UART (decoder inlined)

Generated by k230/pipeline/stages/07_package.py.
""")
    print(f"[stage 07] DONE -> {out}")
    for f in sorted(out.iterdir()):
        sz = f.stat().st_size
        print(f"  {f.name:30s} {sz:>10,} B")

if __name__ == "__main__":
    main()
